server {
    listen       80;
    server_name  localhost;

    location / {
        root     path/to/front;
        index    index.html index.htm;
    }
    location /api/ {
        rewrite ^/api^/ /$1 break;
        proxy_pass http://localhost:8080/;
    }
}